version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/store-manager-api
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
      runas: ec2-user