FROM node:erbium-alpine3.14

WORKDIR /app
ENV PORT=3000

ARG MYSQL_HOST
ENV MYSQL_HOST $MYSQL_HOST
ARG MYSQL_USER
ENV MYSQL_USER $MYSQL_USER
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD $MYSQL_PASSWORD

COPY package*.json ./
RUN npm install
COPY ./ ./
CMD ["npm", "start"]

EXPOSE 3000 