name: CI Test Store Manager

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  app-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [14.x, 17.x]
    env:
      MYSQL_USER: "test_store_manager"
      MYSQL_PASSWORD: "test_store_manager"
    services:
      mysql:
        image: mysql:latest
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "StoreManager"
    steps:
        env:
          PORT: "3000"
          HOST: "/"
          MYSQL_HOST: "localhost"
      - uses: actions/checkout@v2
      - name: Start Mysql server with Docker
      - name: Test with Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Starting App
        run: npm start &
      - name: Wait for App to start
        run: sleep 5
      - name: Test
        run: npm test