name: CI Test App
'on':
  push: null
jobs:
  app-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_test_pass
          MYSQL_USER: test_store_manager
          MYSQL_PASSWORD: test_store_manager
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: 'Test with Node ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install dependecies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Starting App
        run: >-
          HOST=/ MYSQL_HOST=127.0.0.1 PORT=3000 MYSQL_USER=test_store_manager
          MYSQL_PASSWORD=test_store_manager npm start &
      - name: Wait for App to start
        run: sleep 5
      - name: Test
        run: >-
          HOST=/ MYSQL_HOST=127.0.0.1 PORT=3000 MYSQL_USER=test_store_manager
          MYSQL_PASSWORD=test_store_manager npm test
