name: CI Test App
'on':
  push: null
jobs:
  app-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    services:
      mysql:
        image: 'mysql:5.7'
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test_store_manager
          MYSQL_PASSWORD: test_store_manager
    steps:
      - uses: actions/checkout@v2
      - name: 'Test with Node ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
        env:
          PORT: 3000
          HOST: /
          MYSQL_HOST: localhost
      - name: Install dependecies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Starting App
        run: >-
          HOST=/ MYSQL_HOST=localhost PORT=3000 MYSQL_USER=test_store_manager
          MYSQL_PASSWORD=test_store_manager npm start &
      - name: Wait for App to start
        run: sleep 5
      - name: Test
        run: >-
          HOST=/ MYSQL_HOST=localhost PORT=3000 MYSQL_USER=root
          MYSQL_PASSWORD=root npm test
